### ISSUE TITLE
How to build it with VS2017?

### ISSUE THREAD

**Issue by ddbb2017** [mity/theme-explorer#1]
Is this repo still maintained?

I'm attempting to build this project with VS 2017.

First off, there's no VS solution included in the source package. So I built it by using File -> New -> Project from Existing Code and by specifying your "src" folder. Then after adding all sorts of missing .libs and removing hardcoded manifest resource there are two main issues:

1. When I'm trying to open the "resources" in VS, it gives me this error:
https://i.imgur.com/zqibY9k.png

2. Even after I managed to compile the code (ignoring multiple warnings), the executable doesn't seem to be showing any themes. Here's a comparison to your binary:
https://i.imgur.com/nCtDZcq.png

**Comment by mity** [comment]
Semi-maintained. I occasionally use the tool, but I do not need to add new features at the moment and I do not want to invest much time in it. If I meet some need to add new features I would revive it. If anybody provides reasonable PR, I'll merge.

MSVC 2017 has direct support for building CMake-based projects. See building instructions in `README.md` for [mctrl](https://github.com/mity/mctrl/blob/master/README.md). It should be the same.

But I probably never tried for Theme Explorer so there might be surprises.

**Comment by mity** [comment]
Just tried. Required a small fix but works for me now.
